# -*- coding: utf-8 -*-
"""RevisaoAv02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQb9t8GgHWkUpUa8kZZyPGXG-Iep8vKz

#Avaliação para Estagiários de Programação
**Empresa:** InovaTech Solutions

**Cargo:** Estagiário em Desenvolvimento de Software

**Duração:** 120 minutos

**Questão 01:** Escreva um programa que peça nome e profissão ao usuário e imprima:
"""



"""**Questão 2:** Escreva um programa que conte quantas letras maiúsculas existem em uma string fornecida pelo usuário.

> *Exemplo: Entrada: "Python" → Saída: "A string 'Python' tem 1 letra(s) maiúscula(s)."*


"""



"""**Questão 3:** Use a estrutura while para somar números digitados pelo usuário até que ele insira 0. Exiba o total."""



"""**Questão 4:** Escreva um programa que
Classifique a idade do usuário em:



> "Criança" (< 12 anos),

> "Adolescente" (12–17 anos),

> "Adulto" (≥ 18 anos).


"""



"""**Questão 5:** Escreva 3 números e calcule a média aritmética."""



"""**Questão 6:** Use a estrutura FOR para imprimir números de 1 a 5 (um por linha)."""



"""**Questão 7:** Escreva uma função que modifique o terceiro elemento da lista para o número digitado pelo usuário.

> Lista: [10, 20, 30, 40]


"""



"""**Questão 8:** Crie uma função calcular_area_retangulo(base, altura) que retorne a área de um retângulo."""



"""**Questão 9:** Escreva um programa que receba duas listas **de mesmo tamanho** e retorne uma nova lista com os elementos intercalados.  
**Exemplo:**  
ENTRADA
```
lista01 = ['a', 'e', 'i', 'o', 'u']  
lista02 = [1, 2, 3, 4, 5]
```
SAÍDA


```
['a', 1, 'e', 2, 'i', 3, 'o', 4, 'u', 5]
```
"""



"""**Questão 10:** Escreva uma função que RETIRE o elemento da lista de acordo com o número da posição digitado pelo usuário.

Lista: [10, 20, 30, 40]
"""

