# -*- coding: utf-8 -*-
"""Treino_Maratona_Programacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYcBaWbZVLbfCx7WhKsIXjNb4CuaU_rD

# TREINAMENTO PARA MARATONA DE PROGRAMAÇÃO

**Professor:** *Emmanoel Monteiro de Sousa Junior*

**Disciplina:** Introdução a lógica de programação e algoritmos

## Regras:

1. Grupos de até 4 alunos;
2. Cada grupo deve eleger um capitão, responsável por comunicar-se com os fiscais;
3. O fiscal verificará a solução diretamente no computador do grupo;
5. Se houver erro, o grupo terá 5 minutos para corrigir e solicitar uma nova revisão que poderá ser realizada por outro fiscal;
6. Cada questão resolvida é marcada no quadro com um check (✓) ao lado do nome do grupo;

## Vitória:

1. Grupo que resolver todas as questões primeiro vence imediatamente.
2. Se o tempo acabar, vence o grupo com mais questões resolvidas.
3. Desempate: Soma dos pesos das questões resolvidas:

*   Fácil: 1 ponto
*   Média: 3 pontos
*   Difícil: 5 pontos

## Restrições

1. Permitido: Documentação oficial do Python (sem acesso a fóruns ou soluções prontas) e IA da IDE de desenvolvimento.
2. Proibido: Copiar código de outros grupos, usar IAs Externas (ex: ChatGPT e DeepSeek).

## Dicas estratégicas

* Comecem pelas questões fáceis para garantir pontos rápidos.
* Dividam as tarefas entre os membros (ex: um cuida da lógica, outro da implementação).

# Questão 1 (Fácil)

Escreva um programa que leia três números inteiros e imprima a soma deles.
"""



"""# Questão 2 (Fácil)

Crie um programa que inverta a ordem de uma lista de 5 elementos fornecida pelo usuário.
"""



"""# Questão 3 (Fácil)

Implemente uma função eh_par(n) que retorna True se o número for par e False caso contrário.
"""



"""# Questão 4 (Fácil)

Ordene uma lista de 5 números usando o algoritmo Bubble Sort e imprima a lista ordenada.
"""



"""# Questão 5 (Média)

Escreva um programa que conte quantas vezes a letra "a" (maiúscula ou minúscula) aparece em uma frase fornecida pelo usuário.
"""



"""# Questão 6 (Média)
Crie uma função primos_ate(n) que retorna uma lista de números primos até n.


"""



"""# Questão 7 (Média)

Faça um programa que some duas matrizes 3x3.
"""



"""# Questão 8 (Média)

Construa um programa que calcule a área de um triângulo retângulo.
"""



"""# Questão 9 (Difícil)

Ordene uma lista de palavras primeiro pelo tamanho (da maior para a menor) e, em caso de empate, alfabeticamente.
"""



"""# Questão 10 (Difícil)

Faça um programa que leia uma lista de números e imprima a frequência (quantas vezes aparece) de cada elemento, na ordem em que os elementos aparecem pela primeira vez.

Exemplo:
Entrada: [5, 2, 8, 2, 5, 5]
"""

